### ISSUE TITLE
which version of arduinoSTL was used in this project?

### ISSUE THREAD

**Issue by prateekkaistha** [deltaxrobot/Delta-X-Firmware#1]
I tried installing arduinoSTL but got this error
error: 'std::size_t' has not been declared
 _UCXXEXPORT void operator delete[](void * ptr, std::size_t) throw(){

**Comment by trungdoanhong** [comment]
Please install Arduino IDE 1.8.10, it is very stable.
**ArduinoSTL** by **Mike Matera** Version 1.1.0

**Comment by prateekkaistha** [comment]
I installed

> Please install Arduino IDE 1.8.10, it is very stable.

I installed version 1.1.0 by Mike (https://www.arduinolibraries.info/libraries/arduino-stl) but gave the forementioned error while compiling

**Comment by trungdoanhong** [comment]
Did you choose Arduino Mega 2560?

**Comment by prateekkaistha** [comment]
> Did you choose Arduino Mega 2560?

yes I have selected Arduino Mega 2560.

**Comment by trungdoanhong** [comment]
Try removing all Arduino IDE and install a lower version

**Comment by prateekkaistha** [comment]
> Try removing all Arduino IDE and install a lower version

I dont't find issue with the Arduino IDE but with the ArduinoSTL version1.1.0 in del_opvs.cpp 
error: 'std::size_t' has not been declared
 _UCXXEXPORT void operator delete[](void * ptr, std::size_t) throw(){

**Comment by trungdoanhong** [comment]
This error is caused by the Arduino IDE version that doesn't match the ArduinoSTL library. A lot of people have this error because they have the latest version of Arduino IDE.

**Comment by prateekkaistha** [comment]
> This error is caused by the Arduino IDE version that doesn't match the ArduinoSTL library. A lot of people have this error because they have 


> This error is caused by the Arduino IDE version that doesn't match the ArduinoSTL library. A lot of people have this error because they have the latest version of Arduino IDE.

Thanks a lot the issue is resolved and the code is compiled the issue was with the ArduinoIDE version
